name: nlp_deliv2
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - pip
  - pip:
    - sklearn-crfsuite
    - torch
    - torchvision
    - torchaudio
    - tqdm
