name: quora_challenge_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - jupyter
  - notebook
  - ipykernel
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - joblib
  - pip:
      - xgboost
